// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FlyingFishMenuWeb.Server.Model;

public partial class MenuItemVariant
{
    public string Id { get; set; }

    public string VariantName { get; set; }

    public decimal? Price { get; set; }

    public string MenuItemId { get; set; }
    public bool? IsVegetarian { get; set; }

    [JsonIgnore]
    public virtual MenuItem MenuItem { get; set; }
}