// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FlyingFishMenuWeb.Server.Model;

public partial class MenuItem
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? IsPopular { get; set; }

    [JsonIgnore]
    public int? CategoryId { get; set; }

    public virtual ItemCategory Category { get; set; }

    public virtual ICollection<MenuItemVariant> MenuItemVariants { get; set; } = new List<MenuItemVariant>();
}