// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

using FlyingFishMenuWeb.Server.Model;

namespace FlyingFishMenuWeb.Server.Data;

public partial class FlyingFishContext : DbContext
{
    public FlyingFishContext(DbContextOptions<FlyingFishContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ItemCategory> ItemCategories { get; set; }

    public virtual DbSet<MenuItem> MenuItems { get; set; }

    public virtual DbSet<MenuItemVariant> MenuItemVariants { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ItemCategory>(entity =>
        {
            entity.Property(e => e.CategoryName).HasColumnName("Category_Name");
            entity.Property(e => e.ImageUrl).IsRequired();
        });

        modelBuilder.Entity<MenuItem>(entity =>
        {
            entity.HasIndex(e => e.CategoryId, "IX_MenuItems_Category_Id");

            entity.Property(e => e.CategoryId).HasColumnName("Category_Id");
            entity.Property(e => e.Description).IsRequired();

            entity.HasOne(d => d.Category).WithMany(p => p.MenuItems).HasForeignKey(d => d.CategoryId);
        });

        modelBuilder.Entity<MenuItemVariant>(entity =>
        {
            entity.HasIndex(e => e.MenuItemId, "IX_MenuItemVariants_MenuItem_Id");

            entity.Property(e => e.MenuItemId).HasColumnName("MenuItem_Id");
            entity.Property(e => e.Price).HasColumnType("decimal(19, 4)");
            entity.Property(e => e.VariantName).HasColumnName("Variant_Name");

            entity.HasOne(d => d.MenuItem).WithMany(p => p.MenuItemVariants).HasForeignKey(d => d.MenuItemId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}